-- AlterTable
ALTER TABLE "Task"
ADD COLUMN "estimateHours" DOUBLE PRECISION NOT NULL DEFAULT 1;

-- AlterTable
ALTER TABLE "User"
ADD COLUMN "longBreakMin" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN "pomodoroMinutes" INTEGER NOT NULL DEFAULT 25,
ADD COLUMN "shortBreakMin" INTEGER NOT NULL DEFAULT 5;
